CREATE TABLE  USER (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(50) NOT NULL,
    lastName VARCHAR(50) NOT NULL
);
CREATE TABLE MEMBER (
    pesel INTEGER PRIMARY KEY,
    user_id INTEGER NOT NULL,
    phoneNumber INTEGER NOT NULL,
    email VARCHAR (255) NOT NULL,
    password VARCHAR (255) NOT NULL,
    book_id INTEGER NOT NULL
);
CREATE TABLE AUTHOR (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    user_id INTEGER NOT NULL,
    book_id INTEGER NOT NULL
);
CREATE TABLE BOOK (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    yearOfPublish SMALLINT,
    borrowed BOOLEAN,
    user_id INTEGER NULL
);
CREATE TABLE BOOK_TYPE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50),
    book_id INTEGER NOT NULL
);




