CREATE TABLE USER (
    pesel INTEGER PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    phoneNumber INTEGER NOT NULL,
    email VARCHAR (255) NOT NULL,
    password VARCHAR (255) NOT NULL,
    book_id INTEGER NULL
);

CREATE TABLE BOOK (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    title VARCHAR(100) NOT NULL,
    yearOfPublish SMALLINT,
    borrowed BOOLEAN,
    user_id INTEGER NULL

);

CREATE TABLE AUTHOR (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    firstName VARCHAR(100) NOT NULL,
    lastName VARCHAR(100) NOT NULL,
    book_id INTEGER NOT NULL
);

CREATE TABLE BOOKTYPE (
    id INTEGER AUTO_INCREMENT PRIMARY KEY,
    type VARCHAR(50),
    book_id INTEGER NOT NULL
);




